name: users_app
description: User app with Google Map

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  firebase_database: ^10.0.7
  fluttertoast: ^8.1.2
  google_maps_flutter: ^2.2.2
  flutter_zoom_drawer: ^3.0.3
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  http: ^0.13.5
  provider: ^6.0.5
  flutter_polyline_points: ^1.0.0
  flutter_geofire: ^2.0.3

dev_dependencies:
  flutter_test: 
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
