name: driver_app
description: A Uber Clone.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.1
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  firebase_database: ^10.0.7
  fluttertoast: ^8.1.2
  google_maps_flutter: ^2.2.2
  salomon_bottom_bar: ^3.3.1
  video_player: ^2.4.9
  http: ^0.13.5
  geolocator: ^9.0.2
  provider: ^6.0.5
  flutter_polyline_points: ^1.0.0
  flutter_geofire: ^2.0.3
  firebase_messaging: ^14.2.1
  assets_audio_player: ^3.0.6
  smooth_star_rating_null_safety: ^1.0.4+2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/vedio/login.mp4
    - assets/music/music_notification.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
